extends: standard

parserOptions:
  env:
    es6: true
  sourceType: module

rules:
  arrow-parens:
  - warn
  - as-needed
  - requireForBlockBody: false
  no-shadow: warn
  no-var: warn
  object-curly-spacing: [ warn, always ]
  prefer-arrow-callback: warn
  prefer-const: warn
  strict: [ warn, global ]

  import/newline-after-import: warn
  import/no-absolute-path: warn
  import/no-dynamic-require: warn
  import/no-extraneous-dependencies: warn
  import/no-mutable-exports: warn
  import/order:
  - warn
  - groups:
    - [ builtin, external ]
    - [ sibling, index ]
    - parent
    newlines-between: always-and-inside-groups

  node/no-unsupported-features: none

  promise/catch-or-return: warn
  promise/no-callback-in-promise: warn
  promise/no-native: none
  promise/no-return-wrap: warn
